# Minimum and Maximum

The minimum and maximum operators determine the smallest and largest input, respectively.
Both functions receive two inputs. Each may be a fixed point number or a quantum register.

## Examples

#### Example 1: Two Quantum Variables Minimum

This code example generates a quantum program that returns a minimum of two arguments.
Both the left and right arguments are defined as quantum variables of size three.

In [1]:
from classiq import *
from classiq.qmod.symbolic import min


@qfunc
def main(a: Output[QNum], b: Output[QNum], res: Output[QNum]) -> None:
    a |= 4
    allocate(3, b)
    hadamard_transform(b)

    res |= min(a, b)

In [2]:
qprog = synthesize(main)

result = sample(qprog)
result

Submitting job to simulator
Job: https://platform.classiq.io/jobs/6b8385ee-c784-4660-b2fc-cdf8e54c7f6c

   a  b  res  counts  probability  bitstring
0  4  6    4     282     0.137695  100110100
1  4  5    4     277     0.135254  100101100
2  4  4    4     260     0.126953  100100100
3  4  1    1     256     0.125000  001001100
4  4  3    3     254     0.124023  011011100
5  4  7    4     248     0.121094  100111100
6  4  0    0     236     0.115234  000000100
7  4  2    2     235     0.114746  010010100

#### Example 2: Float and Quantum Variable Maximum

This code example returns a quantum program with a maximum of two arguments.
Here, the left arg is a fixed-point number $(11.1)_2$ (3.5),
and the right arg is a quantum variable of size three.

In [3]:
from classiq.qmod.symbolic import max


@qfunc
def main(a: Output[QNum], res: Output[QNum]) -> None:
    allocate(3, a)
    hadamard_transform(a)

    res |= max(3.5, a)

In [4]:
qprog = synthesize(main)

result = sample(qprog)
result

Submitting job to simulator
Job: https://platform.classiq.io/jobs/97076274-43f3-42fc-b993-0adfa1139875

   a  res  counts  probability bitstring
0  2  3.5     287     0.140137   0111010
1  1  3.5     284     0.138672   0111001
2  3  3.5     260     0.126953   0111011
3  4  4.0     260     0.126953   1000100
4  6  6.0     258     0.125977   1100110
5  5  5.0     250     0.122070   1010101
6  7  7.0     242     0.118164   1110111
7  0  3.5     207     0.101074   0111000